name: recognition
channels:
  - pytorch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - absl-py=0.7.1=py37_0
  - astor=0.7.1=py_0
  - blas=2.11=openblas
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.15.0=h516909a_1001
  - ca-certificates=2019.6.16=hecc5488_0
  - cairo=1.14.12=h8948797_3
  - certifi=2019.6.16=py37_1
  - cffi=1.12.3=py37h2e261b9_0
  - cudatoolkit=9.0=h13b8566_0
  - cycler=0.10.0=py_1
  - dbus=1.13.6=h746ee38_0
  - editdistance=0.5.3=py37hf484d3e_0
  - expat=2.2.6=he6710b0_0
  - ffmpeg=4.0=hcdf2ecd_0
  - fontconfig=2.13.1=he4413a7_1000
  - freeglut=3.0.0=hf484d3e_5
  - freetype=2.9.1=h8a8886c_1
  - gast=0.2.2=py_0
  - gettext=0.19.8.1=hc5be6a0_1002
  - glib=2.56.2=hd408876_0
  - graphite2=1.3.13=h23475e2_0
  - grpcio=1.16.1=py37hf8bcb03_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.8.0=py37h3010b51_1003
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.2=hba1933b_1
  - icu=58.2=h9c2bf20_1
  - intel-openmp=2019.4=243
  - jasper=2.0.14=h07fcdf6_1
  - jpeg=9c=h14c3975_1001
  - keras-applications=1.0.7=py_1
  - keras-preprocessing=1.0.9=py_1
  - kiwisolver=1.1.0=py37hc9558a2_0
  - libblas=3.8.0=11_openblas
  - libcblas=3.8.0=11_openblas
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libglu=9.0.0=hf484d3e_1
  - libiconv=1.15=h516909a_1005
  - liblapack=3.8.0=11_openblas
  - liblapacke=3.8.0=11_openblas
  - libopenblas=0.3.6=h5a2b251_1
  - libopencv=3.4.2=hb342d67_1
  - libopus=1.3=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.9.1=h8b12597_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.10=h2733197_2
  - libuuid=2.32.1=h14c3975_1000
  - libvpx=1.7.0=h439df22_0
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.9=hea5a465_1
  - lmdb=0.9.24=h516909a_0
  - markdown=3.1.1=py_0
  - matplotlib=3.1.0=py37h5429711_0
  - matplotlib-base=3.1.1=py37hfd891ef_0
  - mkl=2019.4=243
  - mkl-service=2.1.0=py37h516909a_0
  - mkl_fft=1.0.14=py37h516909a_1
  - mkl_random=1.0.4=py37hf2d7682_0
  - mock=3.0.5=py37_0
  - ncurses=6.1=he6710b0_1
  - ninja=1.9.0=py37hfd86e86_0
  - numpy=1.16.4=py37h99e49ec_0
  - numpy-base=1.16.4=py37h2f8d375_0
  - olefile=0.46=py37_0
  - openblas=0.3.3=h9ac9557_1001
  - opencv=3.4.2=py37h6fd60c2_1
  - openssl=1.1.1c=h516909a_0
  - pcre=8.43=he6710b0_0
  - pillow=6.1.0=py37h6b7be26_1
  - pip=19.1.1=py37_0
  - pixman=0.38.0=h7b6447c_0
  - protobuf=3.9.1=py37he1b5a44_0
  - pthread-stubs=0.4=h14c3975_1001
  - py-opencv=3.4.2=py37hb342d67_1
  - pycparser=2.19=py37_0
  - pyparsing=2.4.2=py_0
  - pyqt=5.9.2=py37hcca6a23_2
  - python=3.7.3=h0371630_0
  - python-dateutil=2.8.0=py_0
  - python-lmdb=0.96=py37he1b5a44_0
  - pytorch=1.1.0=py3.7_cuda9.0.176_cudnn7.5.1_0
  - pytz=2019.1=py_0
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=h7b6447c_5
  - scipy=1.1.0=py37he2b7bc3_2
  - setuptools=41.0.1=py37_0
  - sip=4.19.8=py37hf484d3e_1000
  - six=1.12.0=py37_0
  - sqlite=3.29.0=h7b6447c_0
  - tensorboard=1.13.1=py37_0
  - tensorflow=1.13.1=py37h90a7d86_1
  - tensorflow-estimator=1.13.0=py_0
  - termcolor=1.1.0=py_2
  - tk=8.6.9=hed695b0_1002
  - torchvision=0.3.0=py37_cu9.0.176_1
  - tornado=6.0.3=py37h516909a_0
  - tqdm=4.33.0=py_0
  - werkzeug=0.15.5=py_0
  - wheel=0.33.4=py37_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
prefix: /home/mkyang/miniconda3/envs/recognition

